apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-canary
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/KiranBK18/Nginx-Canary.git
    targetRevision: HEAD
    path: k8s/stable-app
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      selfHeal: false
      prune: false
