apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app-stable
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/KiranBK18/Nginx-Canary.git
    targetRevision: HEAD
    path: stable-app
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
